version: "3.1"

services:
    db:
        image: mysql:8.0.19
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: etd
            TZ: utc

    adminer:
        image: adminer:latest
        restart: always
        ports:
            - 9000:8080
        environment:
            TZ: utc